-- Seed podcasts for hackathon (run after schema.sql). Basic info per HACKATHON-OUTLINE.md.
insert into public.podcasts (title, description, category, topics, host_name, host_email, contact_url, cover_image_url, website_url, listener_tier) values
('The Indie Hackers Podcast', 'Conversations with founders building profitable internet businesses.', 'Business', array['startups','saas','bootstrapping'], 'Courtland Allen', 'courtland@indiehackers.com', 'https://www.indiehackers.com/contact', 'https://cdn.indiehackers.com/logo.png', 'https://www.indiehackers.com/podcast', 'mid'),
('How I Built This', 'Stories behind the companies and brands we know.', 'Business', array['entrepreneurship','founders','storytelling'], 'Guy Raz', null, 'https://www.npr.org/contact', 'https://media.npr.org/assets/img/2017/09/12/howibuiltthis_sq-5a1a8b2c6d6e8f0a1b2c3d4e5f6a7b8c9d0e.jpg', 'https://www.npr.org/podcasts/510313/how-i-built-this', 'large'),
('My First Million', 'Two entrepreneurs discuss ideas, trends, and making money.', 'Business', array['business','ideas','money'], 'Sam Parr', null, 'https://www.mfmpod.com/contact', null, 'https://www.mfmpod.com', 'mid'),
('The Tim Ferriss Show', 'Interviews with world-class performers on tactics and routines.', 'Business', array['productivity','lifestyle','performance'], 'Tim Ferriss', null, 'https://tim.blog/contact', null, 'https://tim.blog/podcast', 'large'),
('Marketing School', 'Daily marketing tips in under 10 minutes.', 'Marketing', array['marketing','growth','seo'], 'Neil Patel', null, 'https://neilpatel.com/contact', null, 'https://marketingschool.io', 'mid'),
('Copyblogger', 'Content marketing and copywriting advice.', 'Marketing', array['copywriting','content','copyblogger'], 'Sonia Simone', null, 'https://copyblogger.com/contact', null, 'https://copyblogger.com', 'small'),
('The GaryVee Audio Experience', 'Keynotes and interviews on hustle and marketing.', 'Marketing', array['hustle','social','garyvee'], 'Gary Vaynerchuk', null, 'https://garyvaynerchuk.com/contact', null, 'https://garyvaynerchuk.com/podcast', 'large'),
('Health Hacks', 'Simple health and wellness tips for busy people.', 'Health', array['health','wellness','fitness'], 'Dr. Sarah Chen', 'sarah@healthhacks.io', 'https://healthhacks.io/contact', null, 'https://healthhacks.io', 'small'),
('The Mindset Mentor', 'Mindset and personal development.', 'Health', array['mindset','growth','habits'], 'Rob Dial', null, 'https://themindsetmentor.com/contact', null, 'https://themindsetmentor.com', 'mid'),
('Coaching for Leaders', 'Leadership and coaching insights.', 'Business', array['leadership','coaching','management'], 'Dave Stachowiak', 'dave@coachingforleaders.com', 'https://coachingforleaders.com/contact', null, 'https://coachingforleaders.com', 'mid'),
('The Side Hustle Show', 'Ideas for starting and growing a side business.', 'Business', array['side-hustle','entrepreneurship','ideas'], 'Nick Loper', 'nick@sidehustlenation.com', 'https://www.sidehustlenation.com/contact', null, 'https://www.sidehustlenation.com', 'small'),
('Creator Economy', 'How creators build audiences and monetize.', 'Business', array['creators','youtube','newsletter'], 'Jay Clouse', null, 'https://creatorconomy.com/contact', null, 'https://creatorconomy.com', 'small'),
('Write Now', 'Writing and publishing for authors.', 'Business', array['writing','authors','publishing'], 'Sarah Werner', 'sarah@writenowpod.com', 'https://writenowpod.com/contact', null, 'https://writenowpod.com', 'small'),
('SaaS Revolution', 'B2B SaaS founders and growth.', 'Business', array['saas','b2b','growth'], 'Alex Theuma', null, 'https://saasrevolution.io/contact', null, 'https://saasrevolution.io', 'mid'),
('Startup Stories', 'Early-stage founder interviews.', 'Business', array['startups','founders','fundraising'], 'Maya Johnson', 'maya@startupstories.fm', 'https://startupstories.fm/contact', null, 'https://startupstories.fm', 'small');
